/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.bibliotecainterfaz.vista;

import ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador;

/**
 *
 * @author HP
 */
public class MenuInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInicio.class.getName());
    private BibliotecaControlador controlador;
    private java.util.ResourceBundle mensajes;
    private void cambiarIdioma(String lenguaje, String pais) {
    
    java.util.Locale localizacion = new java.util.Locale(lenguaje, pais);
        
        try {
            
            this.mensajes = java.util.ResourceBundle.getBundle(
            "ec.edu.ups.bibliotecainterfaz.idiomas.mensajes",
            localizacion
        );
            
            
            jLabel1.setText(mensajes.getString("lbl.tituloPrincipal")); 
            btnEspanol.setText(mensajes.getString("btn.espanol"));
            btnIngles.setText(mensajes.getString("btn.ingles"));
            
        } catch (Exception e) {
            System.out.println("Error cargando el idioma " + lenguaje + ": " + e.getMessage());
        }
    }
    /**
     * Creates new form MenuInicio
     */
   public MenuInicio(BibliotecaControlador controlador) {
   this.controlador = controlador;
    initComponents(); 
    centrarDiseno();
    
    
    this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); 
    cambiarIdioma("es", "EC");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEspanol = new javax.swing.JButton();
        btnIngles = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DIGITAL DE BIBLIOTECA");

        btnEntrar.setBackground(new java.awt.Color(51, 51, 51));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);

        btnSalir.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnEspanol.setText("español");
        btnEspanol.addActionListener(this::btnEspanolActionPerformed);

        btnIngles.setText("Ingles");
        btnIngles.addActionListener(this::btnInglesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngles)
                    .addComponent(btnEspanol))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnEspanol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngles)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
   if (this.controlador == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: Controlador no inicializado.");
        return;
    }
    VentanaPrincipal principal = new VentanaPrincipal(this.controlador, this.mensajes);
    principal.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    principal.setLocationRelativeTo(null);   
    principal.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInglesActionPerformed
     cambiarIdioma("en", "US");
    }//GEN-LAST:event_btnInglesActionPerformed

    private void btnEspanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspanolActionPerformed
        cambiarIdioma("es", "EC");
    }//GEN-LAST:event_btnEspanolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

       
        java.awt.EventQueue.invokeLater(() -> {
    
    var usuarioDao = new ec.edu.ups.bibliotecainterfaz.idao.UsuarioDaoImpl();
    var libroDao = new ec.edu.ups.bibliotecainterfaz.idao.LibroDaoImpl();
    var prestamoDao = new ec.edu.ups.bibliotecainterfaz.idao.PrestamoDaoImpl();
    
    
    var controlador = new ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador(usuarioDao, libroDao, prestamoDao);
    
    
    new MenuInicio(controlador).setVisible(true);
});
       java.awt.EventQueue.invokeLater(() -> {
        MenuInicio inicio = new MenuInicio(new BibliotecaControlador(
            new ec.edu.ups.bibliotecainterfaz.idao.UsuarioDaoImpl(),
            new ec.edu.ups.bibliotecainterfaz.idao.LibroDaoImpl(),
            new ec.edu.ups.bibliotecainterfaz.idao.PrestamoDaoImpl()
        ));
        
        
        inicio.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        inicio.setVisible(true);
    });
    }
    
    private void centrarDiseno() {
       
        javax.swing.JPanel panelConFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                try {
                    
                    java.net.URL imgURL = getClass().getResource("/ec/edu/ups/bibliotecainterfaz/imagenes/fondo.jpg.jpeg");
                    java.awt.Image img;
                    
                    if (imgURL != null) {
                        img = new javax.swing.ImageIcon(imgURL).getImage();
                    } else {
                       
                        img = new javax.swing.ImageIcon("src/main/java/ec/edu/ups/bibliotecainterfaz/imagenes/fondo.jpg.jpeg").getImage();
                    }
                    
                   
                    if (img.getWidth(null) > 0) {
                        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                    } else {
                       
                        g.setColor(new java.awt.Color(0, 51, 153));
                        g.fillRect(0, 0, getWidth(), getHeight());
                        System.out.println("ERROR: No se encuentra la imagen fondo.jpg");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };

      
        panelConFondo.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(15, 15, 15, 15);
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255)); 
        jLabel1.setText("SISTEMA DIGITAL DE BIBLIOTECA");
        panelConFondo.add(jLabel1, gbc);

      
        gbc.gridy = 1;
        String rutaBase = "C:\\Users\\HP\\Documents\\NetBeansProjects\\BibliotecaInterfaz\\src\\main\\java\\ec\\edu\\ups\\bibliotecainterfaz\\imagenes\\";
        
        java.util.function.BiConsumer<javax.swing.JButton, String> ponerIcono = (btn, archivo) -> {
            try {
                java.awt.Image iconImg = new javax.swing.ImageIcon(rutaBase + archivo).getImage();
                if(iconImg != null && iconImg.getWidth(null) > 0) {
                    
                    btn.setIcon(new javax.swing.ImageIcon(iconImg.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH)));
                }
            } catch(Exception e){}
            
            btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM); 
            btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER); 
            btn.setContentAreaFilled(false); 
            btn.setBorderPainted(false); 
            btn.setFocusPainted(false);
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
        };

       
        ponerIcono.accept(btnEntrar, "entrar.png");
        ponerIcono.accept(btnSalir, "salida.png");
       

        javax.swing.JPanel pnlBotones = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 0));
        pnlBotones.setOpaque(false); 
        pnlBotones.add(btnEntrar);
        pnlBotones.add(btnSalir);
        panelConFondo.add(pnlBotones, gbc);

       
        gbc.gridy = 2;
        javax.swing.JPanel pnlIdiomas = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0));
        pnlIdiomas.setOpaque(false); 
        pnlIdiomas.add(btnEspanol);
        pnlIdiomas.add(btnIngles);
        panelConFondo.add(pnlIdiomas, gbc);

        
        this.setContentPane(panelConFondo);
        this.revalidate();
        this.repaint();
    }
    // cambio para commit

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnEspanol;
    private javax.swing.JButton btnIngles;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
