/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.bibliotecainterfaz.vista;

import ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador;
import java.util.ResourceBundle;

/**
 *
 * @author HP
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private BibliotecaControlador controlador;
    private ResourceBundle mensajes;
    private VistaLibro vistaLibroAbierta;
    private VistaUsuario vistaUsuarioAbierta;
    private VistaPrestamo vistaPrestamoAbierta;
    private VistaDevolucion vistaDevolucionAbierta;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(BibliotecaControlador controlador, ResourceBundle mensajes) {
        this.controlador = controlador;
    this.mensajes = mensajes;
    initComponents();
    ponerFondoMadera();
    this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    if (this.mensajes != null) actualizarIdioma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopContenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLibros = new javax.swing.JMenuItem();
        btnUsuarios = new javax.swing.JMenuItem();
        btnPrestamos = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Biblioteca - UPS");
        setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout desktopContenedorLayout = new javax.swing.GroupLayout(desktopContenedor);
        desktopContenedor.setLayout(desktopContenedorLayout);
        desktopContenedorLayout.setHorizontalGroup(
            desktopContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        desktopContenedorLayout.setVerticalGroup(
            desktopContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        btnLibros.setText("Libros");
        btnLibros.addActionListener(this::btnLibrosActionPerformed);
        jMenu1.add(btnLibros);

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);
        jMenu1.add(btnUsuarios);

        btnPrestamos.setText("Préstamos");
        btnPrestamos.addActionListener(this::btnPrestamosActionPerformed);
        jMenu1.add(btnPrestamos);

        jMenuItem4.setText("Devoluciones");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Idioma");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopContenedor)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopContenedor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (vistaDevolucionAbierta == null || vistaDevolucionAbierta.isClosed()) {
            vistaDevolucionAbierta = new VistaDevolucion(controlador, mensajes);
            desktopContenedor.add(vistaDevolucionAbierta);
        } else {
            vistaDevolucionAbierta.actualizarIdioma(mensajes);
        }
        vistaDevolucionAbierta.setVisible(true);
        traerAlFrente(vistaDevolucionAbierta);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        if (vistaPrestamoAbierta == null || vistaPrestamoAbierta.isClosed()) {
            vistaPrestamoAbierta = new VistaPrestamo(controlador, mensajes);
            desktopContenedor.add(vistaPrestamoAbierta);
        } else {
            vistaPrestamoAbierta.cargarTabla();
            vistaPrestamoAbierta.actualizarIdioma(mensajes);
        }
        vistaPrestamoAbierta.setVisible(true);
        traerAlFrente(vistaPrestamoAbierta);
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        if (vistaUsuarioAbierta == null || vistaUsuarioAbierta.isClosed()) {
            vistaUsuarioAbierta = new VistaUsuario(this.controlador, this.mensajes);
            desktopContenedor.add(vistaUsuarioAbierta);
        } else {
            vistaUsuarioAbierta.cargarTabla();
            vistaUsuarioAbierta.actualizarIdioma(this.mensajes);
        }
        vistaUsuarioAbierta.setVisible(true);
        traerAlFrente(vistaUsuarioAbierta);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
        if (vistaLibroAbierta == null || vistaLibroAbierta.isClosed()) {
            vistaLibroAbierta = new VistaLibro(controlador, mensajes);
            desktopContenedor.add(vistaLibroAbierta);
        } else {
            vistaLibroAbierta.cargarTabla();
            vistaLibroAbierta.actualizarIdioma();
        }
        vistaLibroAbierta.setVisible(true);
        traerAlFrente(vistaLibroAbierta);
    }//GEN-LAST:event_btnLibrosActionPerformed

    private void traerAlFrente(javax.swing.JInternalFrame ventana) {
        try {
            ventana.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            // ignorar, no es critico
        }
        ventana.toFront();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        System.out.println("Ventana Principal lista. Inicie desde MenuInicio.java");
    }
    public void actualizarIdioma() {
    ResourceBundle mensajes = this.mensajes;
    if (mensajes == null) return;

    jMenu1.setText(mensajes.getString("opciones.menu"));
    btnLibros.setText(mensajes.getString("menu.libros"));
    btnUsuarios.setText(mensajes.getString("menu.usuarios"));
    btnPrestamos.setText(mensajes.getString("menu.prestamos"));
    jMenuItem4.setText(mensajes.getString("menu.devoluciones"));
    jMenu2.setText(mensajes.getString("menu.idioma"));

    if (btnUsuariosCentro != null) {
        btnUsuariosCentro.setText(mensajes.getString("menu.usuarios"));
        btnLibrosCentro.setText(mensajes.getString("menu.libros"));
        btnPrestamosCentro.setText(mensajes.getString("menu.prestamos"));
        btnDevolucionesCentro.setText(mensajes.getString("menu.devoluciones"));
    }
}
    
  private void ponerFondoMadera() {
       
        java.awt.Container diseñoOriginal = this.getContentPane();
        
        javax.swing.JPanel panelConFondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                try {
                    java.net.URL urlFondo = getClass().getResource("/ec/edu/ups/bibliotecainterfaz/imagenes/fondo2.jpg");
                    if (urlFondo == null) {
                        urlFondo = getClass().getResource("/ec/edu/ups/bibliotecainterfaz/imagenes/fondo.jpg.jpeg");
                    }
                    if (urlFondo != null) {
                        java.awt.Image img = new javax.swing.ImageIcon(urlFondo).getImage();
                        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                    } else {
                        g.setColor(new java.awt.Color(51, 51, 51));
                        g.fillRect(0, 0, getWidth(), getHeight());
                    }
                } catch (Exception e) {}
            }
        };
        
        panelConFondo.setLayout(new java.awt.BorderLayout());
        
        
        if (diseñoOriginal instanceof javax.swing.JComponent) ((javax.swing.JComponent) diseñoOriginal).setOpaque(false);
        for (java.awt.Component hijo : diseñoOriginal.getComponents()) {
            if (hijo instanceof javax.swing.JComponent) ((javax.swing.JComponent) hijo).setOpaque(false);
        }
        
        panelConFondo.add(diseñoOriginal);
        this.setContentPane(panelConFondo);

        
        btnUsuariosCentro = new javax.swing.JButton("Usuarios");
        btnLibrosCentro = new javax.swing.JButton("Libros");
        btnPrestamosCentro = new javax.swing.JButton("Préstamos");
        btnDevolucionesCentro = new javax.swing.JButton("Devoluciones");
        
        
        btnUsuariosCentro.addActionListener(e -> btnUsuarios.doClick());
        btnLibrosCentro.addActionListener(e -> btnLibros.doClick());
        btnPrestamosCentro.addActionListener(e -> btnPrestamos.doClick());
        btnDevolucionesCentro.addActionListener(e -> jMenuItem4.doClick());

        
        String rutaBase = "/ec/edu/ups/bibliotecainterfaz/imagenes/";
        
      
        java.util.function.BiConsumer<javax.swing.JButton, String> formatearBoton = (btn, archivo) -> {
            try {
                java.net.URL urlIcono = getClass().getResource(rutaBase + archivo);
                if (urlIcono != null) {
                    java.awt.Image iconImg = new javax.swing.ImageIcon(urlIcono).getImage();
                    btn.setIcon(new javax.swing.ImageIcon(iconImg.getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH)));
                }
            } catch(Exception e){}
            
            btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM); 
            btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER); 
            btn.setFont(new java.awt.Font("Segoe UI", 1, 20)); 
            btn.setForeground(java.awt.Color.WHITE); 
            btn.setContentAreaFilled(false); 
            btn.setBorderPainted(false); 
            btn.setFocusPainted(false);
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); 
        };

        
        formatearBoton.accept(btnUsuariosCentro, "usuarios.png");
        formatearBoton.accept(btnLibrosCentro, "libros.png");
        formatearBoton.accept(btnPrestamosCentro, "prestamos.png");
        formatearBoton.accept(btnDevolucionesCentro, "devoluciones.png");

       
        javax.swing.JPanel pnlCentro = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 20));
        pnlCentro.setOpaque(false); 
        pnlCentro.add(btnUsuariosCentro);
        pnlCentro.add(btnLibrosCentro);
        pnlCentro.add(btnPrestamosCentro);
        pnlCentro.add(btnDevolucionesCentro);

        
        desktopContenedor.add(pnlCentro);

        
        desktopContenedor.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pnlCentro.setSize(desktopContenedor.getWidth(), 250);
                pnlCentro.setLocation(0, (desktopContenedor.getHeight() - 250) / 2);
            }
        });
        
        this.revalidate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnLibros;
    private javax.swing.JMenuItem btnPrestamos;
    private javax.swing.JMenuItem btnUsuarios;
    private javax.swing.JDesktopPane desktopContenedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JButton btnUsuariosCentro;
    private javax.swing.JButton btnLibrosCentro;
    private javax.swing.JButton btnPrestamosCentro;
    private javax.swing.JButton btnDevolucionesCentro;
}
