/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.bibliotecainterfaz.vista;

import java.util.ResourceBundle;

/**
 *
 * @author HP
 */
public class VistaPrestamo extends javax.swing.JInternalFrame {
    private ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador controlador;
    private ResourceBundle mensajes;
    /**
     * Creates new form VistaPrestamo
     */
    public VistaPrestamo(ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador controlador, java.util.ResourceBundle mensajes) {
        this.controlador = controlador;
       this.mensajes = mensajes;
        initComponents();
        cargarTabla();
        actualizarIdioma(this.mensajes);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();

        jTextField2.setText("jTextField2");

        setBackground(new java.awt.Color(102, 102, 102));
        setTitle("Prestamos");

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cedula Usuario:");

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo libro:");

        txtCedula.setBackground(new java.awt.Color(153, 153, 153));
        txtCedula.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(0, 0, 0));
        txtCedula.addActionListener(this::txtCedulaActionPerformed);

        txtCodigo.setBackground(new java.awt.Color(153, 153, 153));
        txtCodigo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));

        btnCrear.setText("Prestar libro:");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        btnBuscar.setText("Buscar prestamo:");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estado:");

        txtEstado.setBackground(new java.awt.Color(153, 153, 153));
        txtEstado.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(0, 0, 0));
        txtEstado.setText("Prestado");

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula usuaraio", "Codigo  libro", "Fecha", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblPrestamos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula)
                    .addComponent(txtCodigo)
                    .addComponent(txtEstado)))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnCrear)
                .addGap(34, 34, 34)
                .addComponent(btnBuscar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String cedula = txtCedula.getText().trim();
        String codigo = txtCodigo.getText().trim();

        try {
            controlador.prestarLibro(codigo, cedula);
            cargarTabla();
            javax.swing.JOptionPane.showMessageDialog(this, mensajes.getString("exito.prestamoRegistrado"));
            txtCedula.setText("");
            txtCodigo.setText("");
        } catch (ec.edu.ups.bibliotecainterfaz.excepciones.ValidacionException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMensajeLocalizado(mensajes),
                mensajes.getString("dialogo.error"), javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String codigo = txtCodigo.getText().trim();
    
    if (codigo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, mensajes.getString("error.campoObligatorio").replace("{0}", mensajes.getString("lbl.codigo")));
        return;
    }
    
   
    ec.edu.ups.bibliotecainterfaz.modelo.Libro libro = controlador.buscarLibro(codigo);
    
    if (libro != null) {
        if (!libro.isDisponible()) {
            txtEstado.setText(mensajes.getString("estado.prestado"));
            javax.swing.JOptionPane.showMessageDialog(this,
                java.text.MessageFormat.format(mensajes.getString("msg.libroPrestado"), libro.getTitulo()),
                mensajes.getString("titulo.estadoPrestamo"), javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            txtEstado.setText(mensajes.getString("estado.disponible"));
            javax.swing.JOptionPane.showMessageDialog(this,
                java.text.MessageFormat.format(mensajes.getString("msg.libroDisponible"), libro.getTitulo()),
                mensajes.getString("titulo.estadoPrestamo"), javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, mensajes.getString("error.libroNoEncontrado"), mensajes.getString("dialogo.aviso"), javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    
    
    }//GEN-LAST:event_btnBuscarActionPerformed
    public void cargarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblPrestamos.getModel();
        modelo.setRowCount(0);
        
       
        for (ec.edu.ups.bibliotecainterfaz.modelo.Prestamo p : controlador.getPrestamoDao().listar()) {
            String estadoTexto;
            if (p.getEstado() == ec.edu.ups.bibliotecainterfaz.modelo.EstadoPrestamo.DEVUELTO) {
                estadoTexto = mensajes != null ? mensajes.getString("estado.devuelto") : "Devuelto";
            } else {
                estadoTexto = mensajes != null ? mensajes.getString("estado.activo") : "Activo";
            }
            modelo.addRow(new Object[]{
                p.getUsuario().getCedula(), 
                p.getLibro().getCodigo(), 
                p.getFechaPrestamo().toString(),
                estadoTexto
            });
        }
    }
    
    public void actualizarIdioma(java.util.ResourceBundle mensajes) {
        this.mensajes = mensajes; 
        if (mensajes != null) {
            try {
                jLabel1.setText(mensajes.getString("lbl.cedula"));
                jLabel2.setText(mensajes.getString("lbl.codigo"));
                jLabel3.setText(mensajes.getString("lbl.estado"));
                btnCrear.setText(mensajes.getString("btn.prestamo"));
                btnBuscar.setText(mensajes.getString("btn.buscar"));
                this.setTitle(mensajes.getString("titulo.prestamo"));

                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblPrestamos.getModel();
                modelo.setColumnIdentifiers(new Object[]{
                    mensajes.getString("col.cedula"),
                    mensajes.getString("col.codigo"),
                    mensajes.getString("col.fecha"),
                    mensajes.getString("col.estado")
                });
            } catch (Exception e) {
                System.out.println("Error al actualizar idioma en Prestamos: " + e.getMessage());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblPrestamos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEstado;
    // End of variables declaration//GEN-END:variables
}

