/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.bibliotecainterfaz.vista;

import ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador.IdiomaContext;
import java.util.ResourceBundle;

/**
 *
 * @author HP
 */
public class VistaDevolucion extends javax.swing.JInternalFrame {
private ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador controlador;
private ResourceBundle mensajes;
    /**
     * Creates new form VistaDevolucion
     */
    public VistaDevolucion(ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador controlador, java.util.ResourceBundle mensajes) {
        this.controlador = controlador;
       this.mensajes = mensajes;
        initComponents();
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
       
         
    }
    public void actualizarIdioma() {
    java.util.ResourceBundle mensajes = IdiomaContext.get();

    if (mensajes != null) {
        jLabel1.setText(mensajes.getString("lbl.codigo"));
        jLabel2.setText(mensajes.getString("lbl.cedula"));
        jLabel3.setText(mensajes.getString("lbl.fecha"));
        btnDevolver.setText(mensajes.getString("btn.devolucion"));
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigoLibro = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtFecha = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(102, 102, 102));
        setTitle("Devoluciones");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo del libro:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 39, -1, -1));

        txtCodigoLibro.setBackground(new java.awt.Color(153, 153, 153));
        txtCodigoLibro.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtCodigoLibro.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoLibro.addActionListener(this::txtCodigoLibroActionPerformed);
        getContentPane().add(txtCodigoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 28, 236, 40));

        btnDevolver.setText("Devolver libro:");
        btnDevolver.addActionListener(this::btnDevolverActionPerformed);
        getContentPane().add(btnDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 201, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cedula usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha devolucion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, -1, -1));

        txtCedula.setBackground(new java.awt.Color(153, 153, 153));
        txtCedula.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(0, 0, 0));
        txtCedula.addActionListener(this::txtCedulaActionPerformed);
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 86, 236, 37));

        txtFecha.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 149, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoLibroActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
     String codigo = txtCodigoLibro.getText().trim(); 
        
        if (codigo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el código del libro.");
            return;
        }

        
        boolean exito = controlador.devolverLibro(codigo);

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "Devolución registrada con éxito. El libro está disponible de nuevo.");
            
           
            txtCodigoLibro.setText("");
            
        } else {
           
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se pudo realizar la devolución. Verifique el código.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigoLibro;
    private javax.swing.JSpinner txtFecha;
    // End of variables declaration//GEN-END:variables
}
