/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.bibliotecainterfaz.vista;

import ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador;
import java.util.ResourceBundle;

/**
 *
 * @author HP
 */
public class VistaUsuario extends javax.swing.JInternalFrame {
    private ResourceBundle mensajes;
    private final BibliotecaControlador controlador;

    /**
     * Creates new form VistaUsuario
     */
    public VistaUsuario(ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador controlador, java.util.ResourceBundle mensajes) {
     this.controlador = controlador;
    this.mensajes = mensajes;
    initComponents();
    
  
    if (this.mensajes != null) {
        actualizarIdioma(this.mensajes);
    }
    cargarTabla();

    this.setClosable(true);
    this.setIconifiable(true);
    this.setMaximizable(true);
    this.setResizable(true);
    
    }
    public void actualizarIdioma(java.util.ResourceBundle mensajesNuevos) {
    this.mensajes = mensajesNuevos;

    if (this.mensajes != null) {
        jLabel1.setText(this.mensajes.getString("lbl.cedula"));
        jLabel2.setText(this.mensajes.getString("lbl.nombre"));
        btnCrear.setText(this.mensajes.getString("btn.crear"));
        btnBuscar.setText(this.mensajes.getString("btn.buscar"));
        btnActualizar.setText(this.mensajes.getString("btn.actualizar"));
        btnEliminar.setText(this.mensajes.getString("btn.eliminar"));
        this.setTitle(this.mensajes.getString("titulo.usuarios"));

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblUsuarios.getModel();
        modelo.setColumnIdentifiers(new Object[]{
            this.mensajes.getString("col.cedula"),
            this.mensajes.getString("col.nombre")
        });
    }
}

    public void cargarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblUsuarios.getModel();
        modelo.setRowCount(0);
        for (ec.edu.ups.bibliotecainterfaz.modelo.Usuario u : controlador.getUsuarioDao().listar()) {
            modelo.addRow(new Object[]{u.getCedula(), u.getNombre()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 102, 102));
        setTitle("Usuarios");

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cedula:");

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");

        txtCedula.setBackground(new java.awt.Color(153, 153, 153));
        txtCedula.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(0, 0, 0));
        txtCedula.addActionListener(this::txtCedulaActionPerformed);

        txtNombre.setBackground(new java.awt.Color(153, 153, 153));
        txtNombre.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.addActionListener(this::txtNombreActionPerformed);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cedula", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(txtCedula))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(txtNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnBuscar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String cedula = txtCedula.getText().trim();
        String nombre = txtNombre.getText().trim();

        try {
            controlador.registrarUsuario(cedula, nombre);
            cargarTabla();
            javax.swing.JOptionPane.showMessageDialog(this, mensajes.getString("exito.usuarioRegistrado"));
            txtCedula.setText("");
            txtNombre.setText("");
        } catch (ec.edu.ups.bibliotecainterfaz.excepciones.ValidacionException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMensajeLocalizado(mensajes),
                mensajes.getString("dialogo.error"), javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String cedula = txtCedula.getText().trim();
    
        if (cedula.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, mensajes.getString("error.campoObligatorio").replace("{0}", mensajes.getString("lbl.cedula")));
            return;
        }
    
        ec.edu.ups.bibliotecainterfaz.modelo.Usuario u = controlador.buscarUsuario(cedula);
    
        if (u != null) {
            
            txtNombre.setText(u.getNombre());
            
           
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblUsuarios.getModel();
            for (int i = 0; i < modelo.getRowCount(); i++) {
                if (modelo.getValueAt(i, 0) != null && modelo.getValueAt(i, 0).toString().equals(cedula)) {
                    tblUsuarios.setRowSelectionInterval(i, i); 
                    break; 
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, mensajes.getString("error.usuarioNoEncontrado"), mensajes.getString("dialogo.aviso"), javax.swing.JOptionPane.WARNING_MESSAGE);
            txtNombre.setText(""); 
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String cedula = txtCedula.getText().trim();
        String nombre = txtNombre.getText().trim();

        try {
            controlador.actualizarUsuario(cedula, nombre);
            cargarTabla();
            javax.swing.JOptionPane.showMessageDialog(this, mensajes.getString("exito.usuarioActualizado"));
            txtCedula.setText("");
            txtNombre.setText("");
        } catch (ec.edu.ups.bibliotecainterfaz.excepciones.ValidacionException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMensajeLocalizado(mensajes),
                mensajes.getString("dialogo.error"), javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String cedula = txtCedula.getText().trim();

        if (cedula.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, mensajes.getString("error.campoObligatorio").replace("{0}", mensajes.getString("lbl.cedula")));
            return;
        }

        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this,
            mensajes.getString("btn.eliminar") + " " + cedula,
            mensajes.getString("dialogo.confirmar"), javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            try {
                controlador.eliminarUsuario(cedula);
                cargarTabla();
                javax.swing.JOptionPane.showMessageDialog(this, mensajes.getString("exito.usuarioEliminado"));
                txtCedula.setText("");
                txtNombre.setText("");
            } catch (ec.edu.ups.bibliotecainterfaz.excepciones.ValidacionException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMensajeLocalizado(mensajes),
                    mensajes.getString("dialogo.error"), javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
