/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.bibliotecainterfaz.vista;

import ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador;
import ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador.IdiomaContext;
import java.util.ResourceBundle;

/**
 *
 * @author HP
 */
public class VistaLibro extends javax.swing.JInternalFrame {
private ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador controlador;
private ResourceBundle mensajes;
    /**
     * Creates new form VistaLibro
     */
    public VistaLibro(ec.edu.ups.bibliotecainterfaz.controlador.BibliotecaControlador controlador, java.util.ResourceBundle mensajes) {
        this.controlador = controlador;
        this.mensajes = mensajes;
        initComponents();
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        this.setResizable(true);
    
        
    }
     public void actualizarIdioma() {
        ResourceBundle mensajes = IdiomaContext.get();

        if (mensajes != null) {
            jLabel1.setText(mensajes.getString("lbl.codigo"));
            jLabel2.setText(mensajes.getString("lbl.titulo"));
            jLabel3.setText(mensajes.getString("lbl.autor"));

            btnCrear.setText(mensajes.getString("btn.guardar"));
            btnBuscar.setText(mensajes.getString("btn.buscar"));
            btnEliminar.setText(mensajes.getString("btn.eliminar"));
        }
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(102, 102, 102));
        setTitle("Libros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Titulo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 91, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Autor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 143, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(153, 153, 153));
        txtCodigo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.addActionListener(this::txtCodigoActionPerformed);
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 18, 297, 43));

        txtTitulo.setBackground(new java.awt.Color(153, 153, 153));
        txtTitulo.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.addActionListener(this::txtTituloActionPerformed);
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 79, 297, 43));

        txtAutor.setBackground(new java.awt.Color(153, 153, 153));
        txtAutor.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtAutor.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 131, 297, 43));

        btnCrear.setText("Guardar");
        btnCrear.addActionListener(this::btnCrearActionPerformed);
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 211, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 211, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 211, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 211, -1, -1));

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Titulo", "Autor"
            }
        ));
        jScrollPane2.setViewportView(tblLibros);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 410, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
   String codigo = txtCodigo.getText().trim();
        String titulo = txtTitulo.getText().trim();
        String autor = txtAutor.getText().trim();

        
        if (codigo.isEmpty() || titulo.isEmpty() || autor.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos antes de guardar.");
            return; 
        }

       
        boolean exito = controlador.registrarLibro(codigo, titulo, autor);

        if (exito) {
            
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblLibros.getModel();
            modelo.addRow(new Object[]{codigo, titulo, autor});

            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Libro guardado exitosamente!");
            txtCodigo.setText("");
            txtTitulo.setText("");
            txtAutor.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El libro ya existe o hubo un problema.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
                                                 
        String codigo = txtCodigo.getText().trim();
    
        if (codigo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el código del libro para buscar.");
            return;
        }
   
        ec.edu.ups.bibliotecainterfaz.modelo.Libro l = controlador.buscarLibro(codigo);
    
        if (l != null) {
            
            txtTitulo.setText(l.getTitulo());
            txtAutor.setText(l.getAutor());
            
            
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblLibros.getModel();
            for (int i = 0; i < modelo.getRowCount(); i++) {
                if (modelo.getValueAt(i, 0) != null && modelo.getValueAt(i, 0).toString().equals(codigo)) {
                    tblLibros.setRowSelectionInterval(i, i); 
                    break; 
                }
            }
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Libro no encontrado.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            
            txtTitulo.setText("");
            txtAutor.setText("");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    String codigo = txtCodigo.getText().trim();
        String titulo = txtTitulo.getText().trim();
        String autor = txtAutor.getText().trim();
    
        if (codigo.isEmpty() || titulo.isEmpty() || autor.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos para actualizar.");
            return;
        }
    
        
        boolean exito = controlador.actualizarLibro(codigo, titulo, autor);
    
        if (exito) {
            
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblLibros.getModel();
            
           
            for (int i = 0; i < modelo.getRowCount(); i++) {
                if (modelo.getValueAt(i, 0) != null && modelo.getValueAt(i, 0).toString().equals(codigo)) {
                    modelo.setValueAt(titulo, i, 1); 
                    modelo.setValueAt(autor, i, 2);  
                    break; 
                }
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Libro actualizado correctamente.");
            txtCodigo.setText("");
            txtTitulo.setText("");
            txtAutor.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El libro con ese código no existe.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    String codigo = txtCodigo.getText().trim();
    
        if (codigo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el código del libro que desea eliminar.");
            return;
        }
    
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este libro?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
    
        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            
            boolean exito = controlador.eliminarLibro(codigo);
            
            if (exito) {
                
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblLibros.getModel();
                
                
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    if (modelo.getValueAt(i, 0) != null && modelo.getValueAt(i, 0).toString().equals(codigo)) {
                        modelo.removeRow(i); 
                        break; 
                    }
                }

                javax.swing.JOptionPane.showMessageDialog(this, "Libro eliminado con éxito.");
                txtCodigo.setText("");
                txtTitulo.setText("");
                txtAutor.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El libro no existe.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
